/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ComponentOverviewEntry struct {

	// 1-None/Negligible, 2-Unknown, 3-Low, 4-Medium, 5-High
	Severity int32 `json:"severity,omitempty"`

	// number of the components with certain severity.
	Count int32 `json:"count,omitempty"`
}
