/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ConfigurationsScanAllPolicy struct {

	// The type of scan all policy, currently the valid values are \"none\" and \"daily\"
	Type_ string `json:"type,omitempty"`

	Parameter ConfigurationsScanAllPolicyParameter `json:"parameter,omitempty"`
}
