/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The components overview of the image.
type DetailedTagScanOverviewComponents struct {

	// Total number of the components in this image.
	Total int32 `json:"total,omitempty"`

	// List of number of components of different severities.
	Summary []ComponentOverviewEntry `json:"summary,omitempty"`
}
