/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type HasAdminRole struct {

	// 1-has admin, 0-not.
	HasAdminRole int32 `json:"has_admin_role,omitempty"`
}
