/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type LdapImportUsers struct {

	// selected uid list
	LdapUidList []string `json:"ldap_uid_list,omitempty"`
}
