/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type LdapFailedImportUsers struct {

	// the uid can't add to system.
	LdapUid string `json:"ldap_uid,omitempty"`

	// fail reason.
	Error_ string `json:"error,omitempty"`
}
