/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Manifest struct {

	// The detail of manifest.
	Manifest interface{} `json:"manifest,omitempty"`

	// The config of the repository.
	Config string `json:"config,omitempty"`
}
