/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Password struct {

	// The user's existing password.
	OldPassword string `json:"old_password,omitempty"`

	// New password for marking as to be updated.
	NewPassword string `json:"new_password,omitempty"`
}
