/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type RepPolicyPost struct {

	// The project ID.
	ProjectId int64 `json:"project_id,omitempty"`

	// The target ID.
	TargetId int64 `json:"target_id,omitempty"`

	// The policy name.
	Name string `json:"name,omitempty"`

	// 1-enable, 0-disable
	Enabled int32 `json:"enabled,omitempty"`
}
