/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type RepoSignature struct {

	// The tag of image.
	Tag string `json:"tag,omitempty"`

	// The JSON object of the hash of the image.
	Hashes interface{} `json:"hashes,omitempty"`
}
