/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Role struct {

	// ID in table.
	RoleId int32 `json:"role_id,omitempty"`

	// Description of permissions for the role.
	RoleCode string `json:"role_code,omitempty"`

	// Name the the role.
	RoleName string `json:"role_name,omitempty"`

	RoleMask string `json:"role_mask,omitempty"`
}
