/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type RoleParam struct {

	// Role ID for updating project role member.
	Roles []int32 `json:"roles,omitempty"`

	// Username relevant to a project role member.
	Username string `json:"username,omitempty"`
}
