/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Search struct {

	// Search results of the projects that matched the filter keywords.
	Projects []Project `json:"projects,omitempty"`

	// Search results of the repositories that matched the filter keywords.
	Repositories []SearchRepository `json:"repositories,omitempty"`
}
